In [1]:
import numpy as np
import pandas as pd

In [4]:
import sqlite3 as sql
import matplotlib.pyplot as plt

In [11]:
db = sql.connect('../data/database.sqlite')

In [24]:
df_match = pd.read_sql_query('SELECT * FROM Match', db)
df_team = pd.read_sql_query('SELECT * FROM Team', db)

In [18]:
t = [print(x) for x in df.columns]

id
country_id
league_id
season
stage
date
match_api_id
home_team_api_id
away_team_api_id
home_team_goal
away_team_goal
home_player_X1
home_player_X2
home_player_X3
home_player_X4
home_player_X5
home_player_X6
home_player_X7
home_player_X8
home_player_X9
home_player_X10
home_player_X11
away_player_X1
away_player_X2
away_player_X3
away_player_X4
away_player_X5
away_player_X6
away_player_X7
away_player_X8
away_player_X9
away_player_X10
away_player_X11
home_player_Y1
home_player_Y2
home_player_Y3
home_player_Y4
home_player_Y5
home_player_Y6
home_player_Y7
home_player_Y8
home_player_Y9
home_player_Y10
home_player_Y11
away_player_Y1
away_player_Y2
away_player_Y3
away_player_Y4
away_player_Y5
away_player_Y6
away_player_Y7
away_player_Y8
away_player_Y9
away_player_Y10
away_player_Y11
home_player_1
home_player_2
home_player_3
home_player_4
home_player_5
home_player_6
home_player_7
home_player_8
home_player_9
home_player_10
home_player_11
away_player_1
away_player_2
away_player_3
away_player_4
away_player_5
away_player_6
away_player_7
away_player_8
away_player_9
away_player_10
away_player_11
goal
shoton
shotoff
foulcommit
card
cross
corner
possession
B365H
B365D
B365A
BWH
BWD
BWA
IWH
IWD
IWA
LBH
LBD
LBA
PSH
PSD
PSA
WHH
WHD
WHA
SJH
SJD
SJA
VCH
VCD
VCA
GBH
GBD
GBA
BSH
BSD
BSA

In [50]:
df_match[df_match['foulcommit'].notna()][['date', 'home_team_api_id', 'away_team_api_id', 'foulcommit']]

,date,home_team_api_id,away_team_api_id,foulcommit
1728,2008-08-17 00:00:00,10260,10261,<foulcommit><value><stats><foulscommitted>1</f...
1729,2008-08-16 00:00:00,9825,8659,<foulcommit><value><stats><foulscommitted>1</f...
1730,2008-08-16 00:00:00,8472,8650,<foulcommit><value><stats><foulscommitted>1</f...
1731,2008-08-16 00:00:00,8654,8528,<foulcommit><value><stats><foulscommitted>1</f...
1732,2008-08-17 00:00:00,10252,8456,<foulcommit><value><stats><foulscommitted>1</f...
...,...,...,...,...
25944,2016-05-25 00:00:00,9931,9956,<foulcommit />
25945,2016-05-25 00:00:00,7896,10190,<foulcommit />
25946,2016-05-25 00:00:00,10199,10179,<foulcommit />
25947,2016-05-25 00:00:00,10191,10192,<foulcommit />
25948,2016-05-25 00:00:00,10243,9824,<foulcommit />

In [53]:
short_match = df_match[df_match['foulcommit'].notna()][['date','home_team_api_id', 'away_team_api_id', 'foulcommit']]
short_team = df_team[['team_api_id', 'team_long_name']]
m1 = pd.merge(short_match, short_team, how = 'inner', left_on = 'home_team_api_id', right_on = 'team_api_id', suffixes = ("_x", "_y"))

m2 = pd.merge(m1, short_team, how = 'inner', left_on = 'away_team_api_id', right_on = 'team_api_id', suffixes = ('_x', '_y'))

In [56]:
fouls_teams = m2.rename(
    columns = {'team_long_name_x' : 'home_team_name', 'team_long_name_y' : 'away_team_name'}
).filter(regex = 'date|home|away|foul')

In [187]:
fouls_teams.head()

,date,home_team_api_id,away_team_api_id,foulcommit,home_team_name,away_team_name
0,2008-08-17 00:00:00,10260,10261,<foulcommit><value><stats><foulscommitted>1</f...,Manchester United,Newcastle United
1,2010-08-16 00:00:00,10260,10261,<foulcommit><value><stats><foulscommitted>1</f...,Manchester United,Newcastle United
2,2011-11-26 00:00:00,10260,10261,<foulcommit><value><stats><foulscommitted>1</f...,Manchester United,Newcastle United
3,2012-12-26 00:00:00,10260,10261,<foulcommit><value><stats><foulscommitted>1</f...,Manchester United,Newcastle United
4,2013-12-07 00:00:00,10260,10261,<foulcommit><value><stats><foulscommitted>1</f...,Manchester United,Newcastle United

In [78]:
import lxml.etree as etree

In [96]:
xml = fouls_teams['foulcommit'].iloc[0]
root = etree.fromstring(xml)

In [121]:
print(etree.tostring(root, pretty_print = True).decode())

<foulcommit>
  <value>
    <stats>
      <foulscommitted>1</foulscommitted>
    </stats>
    <event_incident_typefk>37</event_incident_typefk>
    <elapsed>1</elapsed>
    <player2>32569</player2>
    <player1>25518</player1>
    <sortorder>1</sortorder>
    <team>10261</team>
    <n>267</n>
    <type>foulcommit</type>
    <id>378824</id>
  </value>
  <value>
    <stats>
      <foulscommitted>1</foulscommitted>
    </stats>
    <event_incident_typefk>37</event_incident_typefk>
    <elapsed>2</elapsed>
    <player2>24157</player2>
    <player1>30929</player1>
    <sortorder>0</sortorder>
    <team>10261</team>
    <n>277</n>
    <type>foulcommit</type>
    <id>378826</id>
  </value>
  <value>
    <stats>
      <foulscommitted>1</foulscommitted>
    </stats>
    <event_incident_typefk>37</event_incident_typefk>
    <elapsed>3</elapsed>
    <player2>24148</player2>
    <player1>29581</player1>
    <sortorder>1</sortorder>
    <team>10261</team>
    <n>254</n>
    <type>foulcommit</type>
    <id>378830</id>
  </value>
  <value>
    <stats>
      <foulscommitted>1</foulscommitted>
    </stats>
    <event_incident_typefk>37</event_incident_typefk>
    <elapsed>5</elapsed>
    <player2>40565</player2>
    <player1>30373</player1>
    <sortorder>0</sortorder>
    <team>10260</team>
    <n>256</n>
    <type>foulcommit</type>
    <id>378841</id>
  </value>
  <value>
    <stats>
      <foulscommitted>1</foulscommitted>
    </stats>
    <event_incident_typefk>320</event_incident_typefk>
    <elapsed>10</elapsed>
    <player2>30829</player2>
    <subtype>pushing</subtype>
    <player1>29581</player1>
    <sortorder>0</sortorder>
    <team>10261</team>
    <n>275</n>
    <type>foulcommit</type>
    <id>378894</id>
  </value>
  <value>
    <stats>
      <foulscommitted>1</foulscommitted>
    </stats>
    <event_incident_typefk>37</event_incident_typefk>
    <elapsed>13</elapsed>
    <player2>25518</player2>
    <player1>24157</player1>
    <sortorder>0</sortorder>
    <team>10260</team>
    <n>261</n>
    <type>foulcommit</type>
    <id>378913</id>
  </value>
  <value>
    <stats>
      <foulscommitted>1</foulscommitted>
    </stats>
    <event_incident_typefk>37</event_incident_typefk>
    <elapsed>19</elapsed>
    <player2>30362</player2>
    <player1>24228</player1>
    <sortorder>6</sortorder>
    <team>10261</team>
    <n>260</n>
    <type>foulcommit</type>
    <id>378974</id>
  </value>
  <value>
    <stats>
      <foulscommitted>1</foulscommitted>
    </stats>
    <event_incident_typefk>37</event_incident_typefk>
    <elapsed>27</elapsed>
    <player2>30360</player2>
    <player1>24157</player1>
    <sortorder>0</sortorder>
    <team>10260</team>
    <n>268</n>
    <type>foulcommit</type>
    <id>379035</id>
  </value>
  <value>
    <stats>
      <foulscommitted>1</foulscommitted>
    </stats>
    <event_incident_typefk>37</event_incident_typefk>
    <elapsed>27</elapsed>
    <player2>38807</player2>
    <player1>24154</player1>
    <sortorder>2</sortorder>
    <team>10260</team>
    <n>282</n>
    <type>foulcommit</type>
    <id>379044</id>
  </value>
  <value>
    <stats>
      <foulscommitted>1</foulscommitted>
    </stats>
    <event_incident_typefk>18</event_incident_typefk>
    <elapsed>33</elapsed>
    <player2>32569</player2>
    <subtype>shirt_pull</subtype>
    <player1>34574</player1>
    <sortorder>1</sortorder>
    <team>10261</team>
    <n>283</n>
    <type>foulcommit</type>
    <id>379100</id>
  </value>
  <value>
    <stats>
      <foulscommitted>1</foulscommitted>
    </stats>
    <event_incident_typefk>320</event_incident_typefk>
    <elapsed>36</elapsed>
    <player2>32569</player2>
    <subtype>pushing</subtype>
    <player1>37799</player1>
    <sortorder>0</sortorder>
    <team>10261</team>
    <n>286</n>
    <type>foulcommit</type>
    <id>379126</id>
  </value>
  <value>
    <stats>
      <foulscommitted>1</foulscommitted>
    </stats>
    <event_incident_typefk>19</event_incident_typefk>
    <elapsed>38</elapsed>
    <player2>33852</player2>
    <subtype>from_behind</subtype>
    <player1>30620</player1>
    <sortorder>0</sortorder>
    <team>10260</team>
    <n>287</n>
    <type>foulcommit</type>
    <id>379154</id>
  </value>
  <value>
    <stats>
      <foulscommitted>1</foulscommitted>
    </stats>
    <event_incident_typefk>19</event_incident_typefk>
    <elapsed>39</elapsed>
    <player2>34574</player2>
    <subtype>from_behind</subtype>
    <player1>32569</player1>
    <sortorder>2</sortorder>
    <team>10260</team>
    <n>290</n>
    <type>foulcommit</type>
    <id>379171</id>
  </value>
  <value>
    <stats>
      <foulscommitted>1</foulscommitted>
    </stats>
    <event_incident_typefk>37</event_incident_typefk>
    <elapsed>42</elapsed>
    <player2>24157</player2>
    <player1>30929</player1>
    <sortorder>0</sortorder>
    <team>10261</team>
    <n>308</n>
    <type>foulcommit</type>
    <id>379195</id>
  </value>
  <value>
    <stats>
      <foulscommitted>1</foulscommitted>
    </stats>
    <event_incident_typefk>320</event_incident_typefk>
    <elapsed>53</elapsed>
    <player2>33852</player2>
    <subtype>pushing</subtype>
    <player1>24157</player1>
    <sortorder>0</sortorder>
    <team>10260</team>
    <n>304</n>
    <type>foulcommit</type>
    <id>379377</id>
  </value>
  <value>
    <stats>
      <foulscommitted>1</foulscommitted>
    </stats>
    <event_incident_typefk>19</event_incident_typefk>
    <elapsed>56</elapsed>
    <player2>34574</player2>
    <subtype>from_behind</subtype>
    <player1>30865</player1>
    <sortorder>0</sortorder>
    <team>10260</team>
    <n>321</n>
    <type>foulcommit</type>
    <id>379390</id>
  </value>
  <value>
    <stats>
      <foulscommitted>1</foulscommitted>
    </stats>
    <event_incident_typefk>19</event_incident_typefk>
    <elapsed>59</elapsed>
    <player2>37799</player2>
    <subtype>from_behind</subtype>
    <player1>30865</player1>
    <sortorder>3</sortorder>
    <team>10260</team>
    <n>313</n>
    <type>foulcommit</type>
    <id>379413</id>
  </value>
  <value>
    <stats>
      <foulscommitted>1</foulscommitted>
    </stats>
    <event_incident_typefk>3</event_incident_typefk>
    <elapsed>68</elapsed>
    <subtype>hands</subtype>
    <player1>24157</player1>
    <sortorder>1</sortorder>
    <team>10260</team>
    <n>328</n>
    <type>foulcommit</type>
    <id>379440</id>
  </value>
  <value>
    <stats>
      <foulscommitted>1</foulscommitted>
    </stats>
    <event_incident_typefk>37</event_incident_typefk>
    <elapsed>70</elapsed>
    <player2>29581</player2>
    <player1>30362</player1>
    <sortorder>1</sortorder>
    <team>10260</team>
    <n>329</n>
    <type>foulcommit</type>
    <id>379444</id>
  </value>
  <value>
    <stats>
      <foulscommitted>1</foulscommitted>
    </stats>
    <event_incident_typefk>37</event_incident_typefk>
    <elapsed>72</elapsed>
    <player2>24148</player2>
    <player1>29581</player1>
    <sortorder>0</sortorder>
    <team>10261</team>
    <n>331</n>
    <type>foulcommit</type>
    <id>379449</id>
  </value>
  <value>
    <stats>
      <foulscommitted>1</foulscommitted>
    </stats>
    <event_incident_typefk>320</event_incident_typefk>
    <elapsed>76</elapsed>
    <player2>32569</player2>
    <subtype>pushing</subtype>
    <player1>29581</player1>
    <sortorder>0</sortorder>
    <team>10261</team>
    <n>339</n>
    <type>foulcommit</type>
    <id>379468</id>
  </value>
  <value>
    <stats>
      <foulscommitted>1</foulscommitted>
    </stats>
    <event_incident_typefk>5</event_incident_typefk>
    <elapsed>78</elapsed>
    <player2>30929</player2>
    <subtype>serious_foul</subtype>
    <player1>24157</player1>
    <sortorder>0</sortorder>
    <team>10260</team>
    <n>341</n>
    <type>foulcommit</type>
    <id>379479</id>
  </value>
  <value>
    <stats>
      <foulscommitted>1</foulscommitted>
    </stats>
    <event_incident_typefk>37</event_incident_typefk>
    <elapsed>80</elapsed>
    <player2>38807</player2>
    <player1>24150</player1>
    <sortorder>0</sortorder>
    <team>10260</team>
    <n>343</n>
    <type>foulcommit</type>
    <id>379488</id>
  </value>
  <value>
    <stats>
      <foulscommitted>1</foulscommitted>
    </stats>
    <event_incident_typefk>5</event_incident_typefk>
    <elapsed>82</elapsed>
    <player2>29581</player2>
    <subtype>serious_foul</subtype>
    <player1>30362</player1>
    <sortorder>0</sortorder>
    <team>10260</team>
    <n>345</n>
    <type>foulcommit</type>
    <id>379502</id>
  </value>
  <value>
    <stats>
      <foulscommitted>1</foulscommitted>
    </stats>
    <event_incident_typefk>37</event_incident_typefk>
    <elapsed>83</elapsed>
    <player2>30929</player2>
    <player1>30829</player1>
    <sortorder>0</sortorder>
    <team>10260</team>
    <n>348</n>
    <type>foulcommit</type>
    <id>379509</id>
  </value>
  <value>
    <stats>
      <foulscommitted>1</foulscommitted>
    </stats>
    <event_incident_typefk>37</event_incident_typefk>
    <elapsed>89</elapsed>
    <player2>24228</player2>
    <player1>30829</player1>
    <sortorder>2</sortorder>
    <team>10260</team>
    <n>352</n>
    <type>foulcommit</type>
    <id>379542</id>
  </value>
  <value>
    <stats>
      <foulscommitted>1</foulscommitted>
    </stats>
    <elapsed_plus>4</elapsed_plus>
    <event_incident_typefk>37</event_incident_typefk>
    <elapsed>90</elapsed>
    <player2>38994</player2>
    <player1>30360</player1>
    <sortorder>0</sortorder>
    <team>10261</team>
    <n>355</n>
    <type>foulcommit</type>
    <id>379571</id>
  </value>
</foulcommit>

In [185]:
unique_elems = []
for child in root:
    if child[0][0].tag not in unique_elems:
        unique_elems += [child[0][0].tag]
    
    for child1 in child[1:]:
        if child1.tag not in unique_elems:
            unique_elems += [child1.tag]
unique_elems

d = {'foul_idx' : []}
for elem in unique_elems:
    d[elem] = []
    
for i, child in enumerate(root):
    d['foul_idx'] += [i]
    d[child[0][0].tag] += [child[0][0].text]
    
    for child1 in child[1:]:
        d[child1.tag] += [child1.text]
    
    key_lengths = [len(d[x]) for x in list(d.keys())]
    for x in list(d.keys()):
        if len(d[x]) < max(key_lengths):
            d[x] += [None]

pd.DataFrame(d)

,foul_idx,foulscommitted,event_incident_typefk,elapsed,player2,player1,sortorder,team,n,type,id,subtype,elapsed_plus
0,0,1,37,1,32569,25518,1,10261,267,foulcommit,378824,None,None
1,1,1,37,2,24157,30929,0,10261,277,foulcommit,378826,None,None
2,2,1,37,3,24148,29581,1,10261,254,foulcommit,378830,None,None
3,3,1,37,5,40565,30373,0,10260,256,foulcommit,378841,None,None
4,4,1,320,10,30829,29581,0,10261,275,foulcommit,378894,pushing,None
5,5,1,37,13,25518,24157,0,10260,261,foulcommit,378913,None,None
6,6,1,37,19,30362,24228,6,10261,260,foulcommit,378974,None,None
7,7,1,37,27,30360,24157,0,10260,268,foulcommit,379035,None,None
8,8,1,37,27,38807,24154,2,10260,282,foulcommit,379044,None,None
9,9,1,18,33,32569,34574,1,10261,283,foulcommit,379100,shirt_pull,None
10,10,1,320,36,32569,37799,0,10261,286,foulcommit,379126,pushing,None
11,11,1,19,38,33852,30620,0,10260,287,foulcommit,379154,from_behind,None
12,12,1,19,39,34574,32569,2,10260,290,foulcommit,379171,from_behind,None
13,13,1,37,42,24157,30929,0,10261,308,foulcommit,379195,None,None
14,14,1,320,53,33852,24157,0,10260,304,foulcommit,379377,pushing,None
15,15,1,19,56,34574,30865,0,10260,321,foulcommit,379390,from_behind,None
16,16,1,19,59,37799,30865,3,10260,313,foulcommit,379413,from_behind,None
17,17,1,3,68,None,24157,1,10260,328,foulcommit,379440,hands,None
18,18,1,37,70,29581,30362,1,10260,329,foulcommit,379444,None,None
19,19,1,37,72,24148,29581,0,10261,331,foulcommit,379449,None,None
20,20,1,320,76,32569,29581,0,10261,339,foulcommit,379468,pushing,None
21,21,1,5,78,30929,24157,0,10260,341,foulcommit,379479,serious_foul,None
22,22,1,37,80,38807,24150,0,10260,343,foulcommit,379488,None,None
23,23,1,5,82,29581,30362,0,10260,345,foulcommit,379502,serious_foul,None
24,24,1,37,83,30929,30829,0,10260,348,foulcommit,379509,None,None
25,25,1,37,89,24228,30829,2,10260,352,foulcommit,379542,None,None
26,26,1,37,90,38994,30360,0,10261,355,foulcommit,379571,None,4

In [148]:
for child in root:
    print(
        "Fouls Committed:",child[0][0].text,
        '\nIncident Type:', child[1].text,
        '\nPlayer 1:', child[4].text,
        '\nPlayer 2:', child[3].text,
        '\nTeam:', child[5].text,
        '\n'
    )

Fouls Committed: 1
Incident Type: 37
Player 1: 25518
Player 2: 32569
Team: 1

Fouls Committed: 1
Incident Type: 37
Player 1: 30929
Player 2: 24157
Team: 0

Fouls Committed: 1
Incident Type: 37
Player 1: 29581
Player 2: 24148
Team: 1

Fouls Committed: 1
Incident Type: 37
Player 1: 30373
Player 2: 40565
Team: 0

Fouls Committed: 1
Incident Type: 320
Player 1: pushing
Player 2: 30829
Team: 29581

Fouls Committed: 1
Incident Type: 37
Player 1: 24157
Player 2: 25518
Team: 0

Fouls Committed: 1
Incident Type: 37
Player 1: 24228
Player 2: 30362
Team: 6

Fouls Committed: 1
Incident Type: 37
Player 1: 24157
Player 2: 30360
Team: 0

Fouls Committed: 1
Incident Type: 37
Player 1: 24154
Player 2: 38807
Team: 2

Fouls Committed: 1
Incident Type: 18
Player 1: shirt_pull
Player 2: 32569
Team: 34574

Fouls Committed: 1
Incident Type: 320
Player 1: pushing
Player 2: 32569
Team: 37799

Fouls Committed: 1
Incident Type: 19
Player 1: from_behind
Player 2: 33852
Team: 30620

Fouls Committed: 1
Incident Type: 19
Player 1: from_behind
Player 2: 34574
Team: 32569

Fouls Committed: 1
Incident Type: 37
Player 1: 30929
Player 2: 24157
Team: 0

Fouls Committed: 1
Incident Type: 320
Player 1: pushing
Player 2: 33852
Team: 24157

Fouls Committed: 1
Incident Type: 19
Player 1: from_behind
Player 2: 34574
Team: 30865

Fouls Committed: 1
Incident Type: 19
Player 1: from_behind
Player 2: 37799
Team: 30865

Fouls Committed: 1
Incident Type: 3
Player 1: 24157
Player 2: hands
Team: 1

Fouls Committed: 1
Incident Type: 37
Player 1: 30362
Player 2: 29581
Team: 1

Fouls Committed: 1
Incident Type: 37
Player 1: 29581
Player 2: 24148
Team: 0

Fouls Committed: 1
Incident Type: 320
Player 1: pushing
Player 2: 32569
Team: 29581

Fouls Committed: 1
Incident Type: 5
Player 1: serious_foul
Player 2: 30929
Team: 24157

Fouls Committed: 1
Incident Type: 37
Player 1: 24150
Player 2: 38807
Team: 0

Fouls Committed: 1
Incident Type: 5
Player 1: serious_foul
Player 2: 29581
Team: 30362

Fouls Committed: 1
Incident Type: 37
Player 1: 30829
Player 2: 30929
Team: 0

Fouls Committed: 1
Incident Type: 37
Player 1: 30829
Player 2: 24228
Team: 2

Fouls Committed: 1
Incident Type: 4
Player 1: 38994
Player 2: 90
Team: 30360

In [117]:
print(root.tag)
for child in root:
    print(child.tag)
    for child1 in child:
        print('\t',child1.tag)
        for child2 in child1:
            print('\t\t', child2.tag, ':', child2.text)

foulcommit
value
	 stats
		 foulscommitted : 1
	 event_incident_typefk
	 elapsed
	 player2
	 player1
	 sortorder
	 team
	 n
	 type
	 id
value
	 stats
		 foulscommitted : 1
	 event_incident_typefk
	 elapsed
	 player2
	 player1
	 sortorder
	 team
	 n
	 type
	 id
value
	 stats
		 foulscommitted : 1
	 event_incident_typefk
	 elapsed
	 player2
	 player1
	 sortorder
	 team
	 n
	 type
	 id
value
	 stats
		 foulscommitted : 1
	 event_incident_typefk
	 elapsed
	 player2
	 player1
	 sortorder
	 team
	 n
	 type
	 id
value
	 stats
		 foulscommitted : 1
	 event_incident_typefk
	 elapsed
	 player2
	 subtype
	 player1
	 sortorder
	 team
	 n
	 type
	 id
value
	 stats
		 foulscommitted : 1
	 event_incident_typefk
	 elapsed
	 player2
	 player1
	 sortorder
	 team
	 n
	 type
	 id
value
	 stats
		 foulscommitted : 1
	 event_incident_typefk
	 elapsed
	 player2
	 player1
	 sortorder
	 team
	 n
	 type
	 id
value
	 stats
		 foulscommitted : 1
	 event_incident_typefk
	 elapsed
	 player2
	 player1
	 sortorder
	 team
	 n
	 type
	 id
value
	 stats
		 foulscommitted : 1
	 event_incident_typefk
	 elapsed
	 player2
	 player1
	 sortorder
	 team
	 n
	 type
	 id
value
	 stats
		 foulscommitted : 1
	 event_incident_typefk
	 elapsed
	 player2
	 subtype
	 player1
	 sortorder
	 team
	 n
	 type
	 id
value
	 stats
		 foulscommitted : 1
	 event_incident_typefk
	 elapsed
	 player2
	 subtype
	 player1
	 sortorder
	 team
	 n
	 type
	 id
value
	 stats
		 foulscommitted : 1
	 event_incident_typefk
	 elapsed
	 player2
	 subtype
	 player1
	 sortorder
	 team
	 n
	 type
	 id
value
	 stats
		 foulscommitted : 1
	 event_incident_typefk
	 elapsed
	 player2
	 subtype
	 player1
	 sortorder
	 team
	 n
	 type
	 id
value
	 stats
		 foulscommitted : 1
	 event_incident_typefk
	 elapsed
	 player2
	 player1
	 sortorder
	 team
	 n
	 type
	 id
value
	 stats
		 foulscommitted : 1
	 event_incident_typefk
	 elapsed
	 player2
	 subtype
	 player1
	 sortorder
	 team
	 n
	 type
	 id
value
	 stats
		 foulscommitted : 1
	 event_incident_typefk
	 elapsed
	 player2
	 subtype
	 player1
	 sortorder
	 team
	 n
	 type
	 id
value
	 stats
		 foulscommitted : 1
	 event_incident_typefk
	 elapsed
	 player2
	 subtype
	 player1
	 sortorder
	 team
	 n
	 type
	 id
value
	 stats
		 foulscommitted : 1
	 event_incident_typefk
	 elapsed
	 subtype
	 player1
	 sortorder
	 team
	 n
	 type
	 id
value
	 stats
		 foulscommitted : 1
	 event_incident_typefk
	 elapsed
	 player2
	 player1
	 sortorder
	 team
	 n
	 type
	 id
value
	 stats
		 foulscommitted : 1
	 event_incident_typefk
	 elapsed
	 player2
	 player1
	 sortorder
	 team
	 n
	 type
	 id
value
	 stats
		 foulscommitted : 1
	 event_incident_typefk
	 elapsed
	 player2
	 subtype
	 player1
	 sortorder
	 team
	 n
	 type
	 id
value
	 stats
		 foulscommitted : 1
	 event_incident_typefk
	 elapsed
	 player2
	 subtype
	 player1
	 sortorder
	 team
	 n
	 type
	 id
value
	 stats
		 foulscommitted : 1
	 event_incident_typefk
	 elapsed
	 player2
	 player1
	 sortorder
	 team
	 n
	 type
	 id
value
	 stats
		 foulscommitted : 1
	 event_incident_typefk
	 elapsed
	 player2
	 subtype
	 player1
	 sortorder
	 team
	 n
	 type
	 id
value
	 stats
		 foulscommitted : 1
	 event_incident_typefk
	 elapsed
	 player2
	 player1
	 sortorder
	 team
	 n
	 type
	 id
value
	 stats
		 foulscommitted : 1
	 event_incident_typefk
	 elapsed
	 player2
	 player1
	 sortorder
	 team
	 n
	 type
	 id
value
	 stats
		 foulscommitted : 1
	 elapsed_plus
	 event_incident_typefk
	 elapsed
	 player2
	 player1
	 sortorder
	 team
	 n
	 type
	 id